name: Lines of Code (LOC) Badge

on:
  push:
    branches:
      - main

jobs:
  count-lines:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Count Lines of Code
        uses: githubocto/repo-visualizer@v0.0.1
        id: loc

      - name: Display LOC
        run: echo "Lines of Code: ${{ steps.loc.outputs.lines }}"
