name: Lines of Code (LOC) Badge

on:
  push:
    branches:
      - main

jobs:
  count-lines:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install cloc
        run: sudo apt-get update && sudo apt-get install -y cloc

      - name: Count Lines of Code
        run: |
          cloc . --quiet --json > loc.json
          total_lines=$(jq '.SUM.code' loc.json)
          echo "Total Lines of Code: $total_lines"
